name: zoomigoo_user
description: "Zoomigoo User (Frontend-only MVP)"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  share_plus: ^10.0.0
  url_launcher: ^6.3.0
  flutter_phone_direct_caller: ^2.1.1
  image_picker: ^1.0.0
  http: ^1.2.2
  webview_flutter: ^4.7.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - lib/core/mocks/mock_places.json
    - lib/core/mocks/mock_rides.json
    - lib/core/mocks/mock_user.json
    - lib/core/mocks/mock_history.json
